name: "Healthcheck: Controller"

on:
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main,develop ]

env:
  CONTROLLER_PATH: src/node/Lightning.Node

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.CONTROLLER_PATH}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.CONTROLLER_PATH}}
