name: Healthcheck Controller Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  Node_PATH: src/node/Lightning.Node

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.NODE_PATH}}
    - name: Build
      run: dotnet build --no-restore
